config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'users#root_redirect' # => redirects to the profile of the user who is signing in to Blocitoff

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @item = current_user.items.new(item_params)

    if @item.save
      flash[:notice] = "Your task \"#{@item.name}\" was added! Go forth and be productive!"
    else
      flash[:alert] = "Oops... Something went wrong. Please refresh and try again."
    end

    redirect_to user_path(current_user)
  end

  def destroy
    @item = current_user.items.find(params[:id]) # also tried current_user.items.find(item_params)

    @item.destroy

    respond_to do |format|
      format.html { redirect_to(root_path) }
      format.js
    end
  end

private

  def item_params
    params.require(:item).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @items = @user.items
    @item = Item.new
  end

  def root_redirect # => redirects a user upon login to their Profile/Task List /users/:id
    redirect_to user_path(current_user)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for [current_user, @item] do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.submit "Add Task", :class => 'btn btn-default'%>
 <% end %>

app/views/items/_item.html.erb
<tr id="item-<%= item.id %>">
  <td><%= item.name %></td>
  <td><span class=""><%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %></span></td> <%# this is basically x - (y+7) = time remaining %>
  <td><%= link_to "", user_item_path(current_user, item), method: :delete, class: 'glyphicon glyphicon-ok check', remote: true %></td><%# Remember to pass in the parameters to the URL that the Action's route needs to function or you will hit errors.  This would not work without (current_user, item) %>
</tr>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').hide();

  $('.flash').prepend("<div class='alert alert-success'>Way to go! You completed something off your list. You rock!<button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
  // Add alert after successful deletion "task completion" with AJAX.
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'>There was a problem when we tried to complete your item. Please try again.<button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato:400,700,700italic,900,400italic,900italic|Merriweather:400,300,400italic,300italic' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default ">
    <div class="container">
      <%= link_to 'BlocItOff', root_path, :class => 'navbar-brand' %>
      <div class="user-session pull-right">
        <% if user_signed_in? %>
        Welcome, <%= current_user.email %> |
        <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:warning] %>
          <div class=" alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<h2 class="media-heading greeting">Tasks for <%= @user.email %></h2>
<div class="media-heading time-info">
  <p><em>Tasks not completed within 7 days will dissappear.</em></p>
</div>
<div class="media">
  <div class="media-body">
    <table class="table table-striped">
        <tr>
          <th>Task</th>
          <th>Time Remaining</th>
          <th>Complete Task</th>
        </tr>
      <%= render @items %>
    </table>
  </div>

  <div class="form">
    <%= render partial: "items/form" %>
  </div>
  <br>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <h1>Welcome to BlocItOff</h1>
<% else %>
  <h1>Welcome to Blocitoff</h1>
<% end %>

<p>This is the home page for Blocitoff.</p>